title: "Posts"
remote_theme: RMWinslow/just-the-docs-tweaked
search_enabled: true
page_excerpts: true

author: "Robert Winslow"

gh_edit_link: false  # show or hide edit this page link
last_edit_timestamp: true

compress_html:
  ignore:
    envs: all


plugins:
  - jekyll-seo-tag



just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    posts:
      # Give the collection a name
      name: Testt
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
