title: "Posts"
remote_theme: RMWinslow/just-the-docs-tweaked
search_enabled: true
page_excerpts: true

author: "Robert Winslow"

gh_edit_link: false  # show or hide edit this page link
last_edit_timestamp: true

compress_html:
  ignore:
    envs: all


plugins:
  - jekyll-seo-tag

